nodes = {
  
  :node1 => {
    :box_name => "centos/7",
    :box_version => "1902.01",

  },
  
  :node2 => {
    :box_name => "centos/7",
    :box_version => "1902.01",

	},

  :db1 => {
    :box_name => "centos/7",
    :box_version => "1902.01",

  },
  
  :db2 => {
    :box_name => "centos/7",
    :box_version => "1902.01",

  },

  :db3 => {
    :box_name => "centos/7",
    :box_version => "1902.01",

  },

  :dbproxy => {
    :box_name => "centos/7",
    :box_version => "1902.01",

  },
  
}

Vagrant.configure(2) do |config|
  nodes.each do |boxname, boxconfig|

    ### Configure shared folders between host and guest VM
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
        
    config.vm.define "node1" do |node1|
      node1.vm.network :forwarded_port, host:8081, guest: 80, auto_correct: true
      node1.vm.network "private_network", ip: "192.168.100.11", adapter: 2
      node1.vm.network "private_network", ip: "10.0.0.11", adapter: 3
    end

    config.vm.define "node2" do |node2|
      node2.vm.network :forwarded_port, host:8082, guest: 80, auto_correct: true
      node2.vm.network "private_network", ip: "192.168.100.12", adapter: 2
      node2.vm.network "private_network", ip: "10.0.0.12", adapter: 3
    end
    
    config.vm.define "db1" do |db1|
      db1.vm.network "private_network", ip: "10.0.0.13", adapter: 2
    end

    config.vm.define "db2" do |db2|
      db2.vm.network "private_network", ip: "10.0.0.14", adapter: 2
    end

    config.vm.define "db3" do |db2|
      db2.vm.network "private_network", ip: "10.0.0.15", adapter: 2
    end

    config.vm.define "dbproxy" do |dbproxy|
      dbproxy.vm.network "private_network", ip: "192.168.100.20", adapter: 2
      dbproxy.vm.network "private_network", ip: "10.0.0.20", adapter: 3
    end

    config.vm.define boxname do |box|

    box.vm.box = boxconfig[:box_name]
    box.vm.host_name = boxname.to_s
      

	  box.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "256"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      vb.cpus = 1 
    end
    config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/home/kntrbs/.ssh/id_vagrant.pub").first.strip
    s.inline = <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
    end
    #box.vm.provision "ansible" do |ansible|
    #  ansible.playbook = "site.yml"
    #  ansible.become = true
    #end
    
    end
  end
end
